-- Deprecated bootstrap artifact.
-- The current schema is initialized from `prisma/schema.prisma` via:
--   npm run db:init
-- which now runs `prisma db push --force-reset --skip-generate` and then seeds
-- the direct paid reservation demo data.
